# Generated by Django 4.2.7 on 2024-02-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
