# Generated by Django 5.0.1 on 2024-01-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Products'},
        ),
    ]
