# Generated by Django 4.2.7 on 2024-02-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_is_delivered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveredProduct',
        ),
    ]
