# Generated by Django 4.2.7 on 2024-01-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prd_img',
            new_name='product_img',
        ),
    ]
