# Generated by Django 4.2.7 on 2024-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_prd_img_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
