# Generated by Django 4.2.7 on 2024-01-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_products_category_alter_products_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name_plural': 'Products'},
        ),
    ]
